// Code generated by optionGen. DO NOT EDIT.

package main

import "log"

type CatOptions struct {
	sounds string
	food   (*string)
	Walk   func()
}

type CatOp func(option *CatOptions)

func CatOpWith_sounds(value string) CatOp { return func(option *CatOptions) { option.sounds = value } }
func CatOpWith_food(value *string) CatOp  { return func(option *CatOptions) { option.food = value } }
func CatOpWith_Walk(value func()) CatOp   { return func(option *CatOptions) { option.Walk = value } }

func _NewCatOptions() CatOptions {
	return CatOptions{
		sounds: "Meow",
		food:   nil,
		Walk: func() {
			log.Println("Walking")
		},
	}
}
